### ISSUE TITLE
Discussion on API spec - Management of water zones

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/PopulationDensityData#6]
During meeting held on 7th february, open questions were raised:

* **Information in water zones**: Operators and therefore API can only provide data of those zones where it is operating. Water zones are not considered and current implementation will provive an error in case the requested zone includes a water zone. 
* Dimetor proposes to only provide "nonData" or null response for those specific cells, but not a complete error, concious of the multiple cases where flights will indeed consider wateer zones due to the expected low population density.

Participants are invited to provide their view about this issue &rarr;

**Comment by jgarciahospital** [comment]
### Proposed WF (discussed in the meeting and based on offline discussions)

1. For request containing areas totally outside of the operator's reach, response should be:

- Empty response/array --> Dimetor, Telefonica
- Error -->

2. For mixed areas, including cells with a value available and other with no data (outside the operator's reach):

- Only cells for the zones with a real value --> Telefonica
- Cells for the complete request zone with no density value --> 

**To open again discussion focusing on geohash format. Feedback required previous to next meeting.** Companies are invited to provide their preference before next meeting (06 March)

**Comment by Sachinsiso** [comment]
> "For request containing areas totally outside of the operator's reach" 

How will developers be able to differentiate between an empty response caused by the requested area being outside the operator's reach and other potential reasons for an empty response? Are we planning to include any status or message in the response to provide clarity, such as:
```
{
  "status": "outside_operator_reach",
  "data": []
}
```


> For mixed areas, including cells with a value available and other with no data (outside the operator's reach):

Vodafone: _Cells for the complete requested zone (with values where available) and Empty array for cells outside the operator's reach_. I believe, this approach will ensure that developers receive relevant data for the parts of the zone within the operator's coverage and acknowledges the areas outside their reach.

**Comment by gregory1g** [comment]
Suggestion: add a status like @Sachinsiso described for every geohash cell in the respond, because the this the level where this information is needed. It makes sense to make it optional, so service can skip it for cells where everything is "ok".

List of possible statuses can be enhanced later. for example, we, most probably will need something like "below_privacy_threshold"

**Comment by jgarciahospital** [comment]
Update from last meeting [06/03 Minutes](https://wiki.camaraproject.org/display/CAM/2024-03-06+Population+Density+Data+-+Meeting+Minutes)

Complete response Status is proposed for handling both situations:

- Partial response, if only some areas are not included in the response due to the
- Empty response, if no area is managed by operator and, therefore, no information can be provided.

Proposed values (to be agreed):
"enum": ["OK_SUPPORTED_AREA", "PART_OF_ AREA_NOT_SUPPORTED ", "AREA_NOT_SUPPORTED"] 

@gregory1g "low density" already included as a density value for a specific zone and time, where no enough population implies no data can be provided for privacy matters.

**Comment by sachinvodafone** [comment]
Hi @jgarciahospital Could we consider renaming 'OK_SUPPORTED_AREA' to 'AREA_SUPPORTED'? The latter seems clearer and more directly conveys the idea of the area being supported without using 'OK'.

**Comment by jgarciahospital** [comment]
Update from last meeting [20/03 Minutes](https://wiki.camaraproject.org/display/CAM/2024-03-20+Population+Density+Data+-+Meeting+Minutes)

Values for status (initial proposal): "enum": ["AREA_SUPPORTED", "PART_OF_ AREA_NOT_SUPPORTED", "AREA_NOT_SUPPORTED"]



**Agreed WF**

→ offline discussion on partial responses.

→ agreed on the values for the status parameter

**Comment by jgarciahospital** [comment]
Decision: Support async endpoint for bigger and smaller areas, also consider to define a size limitation (area, duration and granularity) (To be defined in issue #7). The response will be part of the API response body, not considering external file link. Only identified limitation is on the calculation time, not in the response size. Async mechanism to be discussed in #20, first code consideration in #21
